#!/usr/bin/env bash

AWS_IMAGE_ID=ami-...
AWS_SERVER_NAME=...
AWS_INSTANCE_TYPE=t3.nano
AWS_KEY_NAME=...
AWS_SUBNET_ID=subnet-...
AWS_SECURITY_GROUPS_IDS="sg-... sg-..."
AWS_VOLUME_SIZE=32
AWS_PEM_KEY_PATH=~/.ssh/[...].pem
